web-app-service/Web/Controllers/SearchController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Core.Entities.References;
using Core.Gateway;
using Core.Services;
using Microsoft.AspNetCore.Mvc;
using Web.Models;
using Web.Utils;
using Web.Utils.Extensions;

namespace Web.Controllers
{
	public class SearchController : Controller
	{
		[HttpGet]
		public async Task<JsonResult> Search([FromServices] IReferenceSearchService service, [FromQuery] string prefix)
		{
			var results = service.Search(prefix, new RequestParams{Limit = 12});
			return Json(new
			{
				Success = true,
				Content = await this.RenderViewAsync("Header/_SearchResultsPartial", FormViewModel(results), true)
			});
		}

		private List<SearchResultViewModel> FormViewModel(List<SneakerReference> references)
		{
			return references.CastExtend<SneakerReference, SearchResultViewModel>();
		}
	}
}

web-app-service/Web/Views/Shared/Header/_IconNavPartial.cshtml
@using Web.Utils.Helpers
@using Microsoft.AspNetCore.Identity
@using Core.Entities.Users
@inject SignInManager<User> SignInManager

<nav class="icon-nav">
	<ul>
		<li class="theme dark">
			@Html.VectorIconRender("theme.svg") @*TODO Nastya sunny easter egg*@
		</li>
		<li class="account expandable">
			@Html.VectorIconRender("user.svg")
			@if (!SignInManager.IsSignedIn(User))
			{
				<ul>
					<li class="button header-button" id="login-btn">
						<span>Login</span>
					</li>
					<li class="button header-button-strong" id="sign-up-btn">
						<span>Sing Up</span>
					</li>
				</ul>
			}
		</li>
		<li class="favorite">
			<a asp-controller="Profile" asp-action="Profile" asp-route-mode="favorite">
				@Html.VectorIconRender("favorite.svg")
			</a>
		</li>
		<li class="search">
			<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
				<g id="search-path">
					<path d="M10 18a7.952 7.952 0 0 0 4.897-1.688l4.396 4.396l1.414-1.414l-4.396-4.396A7.952 7.952 0 0 0 18 10c0-4.411-3.589-8-8-8s-8 3.589-8 8s3.589 8 8 8zm0-14c3.309 0 6 2.691 6 6s-2.691 6-6 6s-6-2.691-6-6s2.691-6 6-6z"/><path d="M11.412 8.586c.379.38.588.882.588 1.414h2a3.977 3.977 0 0 0-1.174-2.828c-1.514-1.512-4.139-1.512-5.652 0l1.412 1.416c.76-.758 2.07-.756 2.826-.002z"/>
				</g>
				<g>
					<path d="M10 2c-4.411 0-8 3.589-8 8s3.589 8 8 8a7.952 7.952 0 0 0 4.897-1.688l4.396 4.396l1.414-1.414l-4.396-4.396A7.952 7.952 0 0 0 18 10c0-4.411-3.589-8-8-8z"/>
				</g>
			</svg>
		</li>
	</ul>
</nav>

web-app-service/Web/Views/Shared/Header/_MainNavPartial.cshtml
@using Web.Handlers.Menu
@inject MenuBuilder<ShopMenuContent> ShopMenuBuilder;

<nav class="main_nav">
	<ul>
		<li>
			<a asp-controller="Home" asp-action="Index">HOME</a>
		</li>
		<li class="expandable">
			<a asp-controller="Profile" asp-action="Profile">PROFILE</a>
			<div class="sub-panel">
				<ul>
					<li>
						<a asp-action="Profile" asp-controller="Profile">ACCOUNT</a>
					</li>
					<li>
						<a asp-action="Profile" asp-controller="Profile" asp-route-mode="buying">BUYING</a>
					</li>
					<li>
						<a asp-action="Profile" asp-controller="Profile" asp-route-mode="selling">SELLING</a>
					</li>
					<li>
						<a asp-action="Profile" asp-controller="Profile" asp-route-mode="favorite">FAVORITE</a>
					</li>
					<li>
						<a asp-action="Profile" asp-controller="Profile" asp-route-mode="payment">PAYMENT</a>
					</li>
					<li>
						<a asp-action="Profile" asp-controller="Profile" asp-route-mode="settings">SETTINGS</a>
					</li>
				</ul>
			</div>
		</li>
		<li class="expandable">
			<a asp-controller="Shop" asp-action="References">SHOP</a>
			@ShopMenuBuilder.RenderMenu(Html)
		</li>
		<li class="expandable">
			<a asp-controller="Sell" asp-action="NewProduct">SELL</a>
			<div class="sub-panel">
				<ul>
					<li>
						<a asp-action="NewProduct" asp-controller="Sell">FIND YOUR KICKS</a>
					</li>
					<li>
						<a asp-action="SetDetails" asp-controller="Sell">START FROM SCRATCH</a>
					</li>
					<li>
						<a asp-action="Profile" asp-controller="Profile" asp-route-mode="selling">SOLD PRODUCTS</a>
					</li>
					<li>
						<a asp-action="Profile" asp-controller="Profile" asp-route-mode="selling">ALL PRODUCTS</a>
					</li>
					<li>
						<a asp-action="Profile" asp-controller="Profile" asp-route-mode="payment">PAYMENT</a>
					</li>
				</ul>
			</div>
		</li>
		<li>
			<a asp-controller="About" asp-action="About">ABOUT</a>
		</li>
		<li>
			<a asp-controller="Contact" asp-action="Contact">CONTACT</a>
		</li>
	</ul>
</nav>

web-app-service/Web/Views/Shared/Header/_MobileMenuPartial.cshtml
@using Web.Utils.Helpers

<div class="menu trans_400">
	<div class="menu-container">
		<div class="slider-menu-content">
			<div class="slider-menu-search">
				<form action="#">
					@Html.VectorIconRender("search.svg")
					<input type="search" required="required" class="menu-search-input">
				</form>
			</div>
			<ul class="slider-menu-nav">
				<li class="slider-menu-item">
					<a asp-controller="Home" asp-action="Index">Home</a>
				</li>
				<li class="slider-menu-item">
					<a asp-controller="Home" asp-action="Index">Profile</a>
				</li>
				<li class="slider-menu-item">
					<a asp-controller="Shop" asp-action="References">Shop</a>
				</li>
				<li class="slider-menu-item">
					<a asp-controller="Sell" asp-action="NewProduct">Sell</a>
				</li>
				<li class="slider-menu-item">
					<a asp-controller="Home" asp-action="Index">About</a>
				</li>
				<li class="slider-menu-item">
					<a asp-controller="Contact" asp-action="Contact">Contacts</a>
				</li>
			</ul>
		</div>
	</div>
	<div class="menu-social">
		@{
			await Html.RenderPartialAsync("_SocialPartial");
		}
	</div>
</div>

web-app-service/Web/Views/Shared/Header/_SearchPartial.cshtml
@using Web.Utils.Helpers
@using Core.Entities.Users
@using Microsoft.AspNetCore.Identity


<div class="search-panel">
	<div class="search-panel-content">
		<div class="search-header">
			<form asp-controller="Search" asp-action="Search" method="get">
				@Html.VectorIconRender("search.svg")
				<input type="search" class="search_input" required="required">
				<button type="button" class="close-button"></button>
			</form>
		</div>
		<div class="search-results">
			@{
				await Html.RenderPartialAsync("Header/_SearchResultsPartial", new List<SearchResultViewModel>());
			}
		</div>
	</div>
</div>

web-app-service/Web/Views/Shared/Header/_SearchResultsPartial.cshtml
@using Web.Utils.Helpers
@using Microsoft.AspNetCore.Identity
@using Core.Entities.Users
@inject SignInManager<User> SignInManager;
@model List<SearchResultViewModel>

@if (Model is null || !Model.Any())
{
	await Html.RenderPartialAsync("Header/_SearchNoResultsPartial");
	return;
}
<div class="results-view grid">
@foreach (var result in Model)
{
	if (result == null)
	{
		continue;
	}
	var price = result.Price != 0m ? $"${result.Price}" : string.Empty;
	<div class="result-cell" id="@result.UniqueID">
		<div class="info-header">
			<div class="price">@price</div>
		</div>
		<div class="thumb">
			<img src="@result.ImagePath" alt="">
		</div>
		<div class="info-footer">
			<div class="brand-title">
				<a class="underline" asp-action="Brand" asp-route-brandID=@result.Brand.Name asp-controller="Shop">
					@Html.DisplayFor(modelItem => result.BrandName)
				</a>
			</div>
			<div class="model-title">
				@*TODO link to model page*@
				<a class="underline" asp-action="ReferenceItem" asp-route-referenceId=@result.UniqueID asp-controller="Shop">
					@Html.DisplayFor(modelItem => result.ModelName)
				</a>
			</div>
			<div class="description">
				@result.Description
			</div>
			@if (SignInManager.IsSignedIn(Context.User))
			{
				<div class="favorite">
					<input type="checkbox" value="true" @(result.Liked ? "checked" : "")/>
					@Html.VectorIconRender("favorite.svg")
				</div>
			}
		</div>
	</div>
}
</div>